<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.xuezi</groupId>
    <artifactId>xuezi-plus-content</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>xuezi-plus-content</name>
    <description>xuezi-plus-content</description>
    <parent>
        <artifactId>xuezi-plus-parent</artifactId>
        <groupId>com.xuezi</groupId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../xuezi-plus-parent</relativePath>
    </parent>
    <packaging>pom</packaging>
    <modules>
        <module>xuezi-plus-content-api</module>
        <module>xuezi-plus-content-service</module>
        <module>xuezi-plus-content-model</module>
    </modules>
</project>
